package ucr.group1.event;

/**
 * Created by Daniel and Gonzalo on 21/2/2017.
 */
public enum EventType {
    A_NEW_QUERY_IS_REQUESTING,
    A_QUERY_IS_FINISHED,
    EXIT_CLIENT_MANAGEMENT_MODULE,
    EXIT_PROCESSES_MANAGEMENT_MODULE,
    EXIT_VERIFICATION_MODULE,
    EXIT_TRANSACTIONS_MODULE,
    EXIT_EXECUTION_MODULE,
    KILL
}
