package ucr.group1.event;

/**
 * Created by Daniel on 21/2/2017.
 */
public enum EventType {
    A_NEW_QUERY_IS_REQUESTING,
    RETURN_TO_CLIENT_MANAGEMENT_MODULE,
    A_QUERY_IS_FINISHED,
    ENTER_PROCESSES_MANAGEMENT_MODULE,
    EXIT_PROCESSES_MANAGEMENT_MODULE,
    ENTER_VERIFICATION_MODULE,
    EXIT_VERIFICATION_MODULE,
    ENTER_TRANSACTIONS_MODULE,
    EXIT_TRANSACTIONS_MODULE,
    ENTER_EXECUTION_MODULE,
    EXIT_EXECUTION_MODULE,
    KILL
}
